[package]
name = "ch19-6"
version = "0.1.0"
authors = ["Jim Hessin <jhessin@gmail.com>"]
edition = "2018"

[dependencies]
hello_macro = {path="../hello_macro"}
hello_macro_derive = {path="../hello_macro_derive"}